In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.4 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.4 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.4 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.4 MB 3.6 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.4 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.4 MB 3.4 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.4 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.4 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.4 MB 3.4 MB/s eta 0:00:02
   ----------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [4]:
## 1. creating arrays

In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [14]:
print(arr_list1.ndim)

1


In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr_list1_2.ndim)

2


In [11]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_25 = np.array([[list1, list2, list3]])
print(arr_list1_25)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(arr_list1_25.ndim)

3


In [17]:
# 2 . numpy array attributes

In [20]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [21]:
print("Shape", arr1.shape)
print("Size", arr1.size)
print("dType", arr1.dtype)
print("n_dim", arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [27]:
 # create 1D array and find its attribute

In [25]:
arr4 = np.array([1,2.0,3.5])
print(arr4)

[1.  2.  3.5]


In [26]:
print("Shape", arr4.shape)
print("Size", arr4.size)
print("dType", arr4.dtype)
print("n_dim", arr4.ndim)

Shape (3,)
Size 3
dType float64
n_dim 1


In [29]:
# create 3D array and  find it's attribute

In [30]:
arr5 = np.array([[[1,20.5, 30.6], [2, 25.3, 28.4], [3, 35.3, 40.9]]])
print(arr5)

[[[ 1.  20.5 30.6]
  [ 2.  25.3 28.4]
  [ 3.  35.3 40.9]]]


In [31]:
print("Shape", arr5.shape)
print("Size", arr5.size)
print("dType", arr5.dtype)
print("n_dim", arr5.ndim)

Shape (1, 3, 3)
Size 9
dType float64
n_dim 3


In [18]:
  # 3 Array initialization method

In [34]:
# zeros array

zero_arry = np.zeros((2,3))
print(zero_arry)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# one array

In [36]:
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [37]:
# full array

In [38]:
full_arr = np.full((3,2), 9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [1]:
# Identity matrix

In [4]:
import numpy as np

In [5]:
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# empty array
print(np.empty(2))

[0. 0.]


In [10]:
# evenly spaced array
print(np.arange(2,6,1))

[2 3 4 5]


In [14]:
# specific number of equally (spaced) values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [16]:
# random values array - float

rf_arr = np.random.rand(3,2)
print(rf_arr)

[[0.76987958 0.26817131]
 [0.19579683 0.99883841]
 [0.48874737 0.86383064]]


In [17]:
# random values array - int

rint_arr = np.random.randint(1,10,(3,3))
print(rint_arr)

[[6 2 9]
 [7 2 3]
 [3 1 1]]


In [19]:
# Array Indexing and Slicing

In [24]:
# INDEXING

a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [21]:
 # Indexing

print(a[1])

3


In [22]:
print(a[4])

9


In [23]:
print(a[-1])

9


In [25]:
# Slicing
# array[start:stop:step]
# stop - index, that is not inclided in output

a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [26]:
print(a[0:3]) # first 3 elememt

[1 3 5]


In [28]:
print(a[-3:]) # Last 3 element

[5 7 9]


In [33]:
print(a[0:5:3])  # middle 3 element with steps

[1 7]


In [34]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [38]:
print(arr2[1] [2]) # indexing

6


In [40]:
print(arr2[1]) # indexing
print(arr2[1:])  # slicing

[4 5 6]
[[4 5 6]]


In [49]:
print(arr2[:, 1]) # slicing

# 2D: [rows, columns]
# 3D: [layers/height, row, columns]

[2 5]


In [51]:
arr3 = np.array([[1,2,3],
                 [4,5,6], [7,8,9]])
print(arr3)
                 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(arr3[0][2])  #indexing
print(arr3[2][2])

3
9


In [63]:
print(arr3[0:, 0]) # 1st col value
print(arr3[0:, 2]) # 2nd column value

[1 4 7]
[3 6 9]


In [70]:
print(arr3[::2, 0]) # jump value 
print(arr3[::, 1:2])  # slicing on cloumns
print(arr3[2::, 1:2]) # slicing on rows and columns

[1 7]
[[2]
 [5]
 [8]]
[[8]]


In [71]:
# 5 Array Reshaping and Flattening

In [74]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [75]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [76]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [77]:
print(reshaped2.flatten())  # it changed multiple dimension to one dimension

[1 2 3 4 5 6]


In [78]:
# 6 Array Stacking and splitting

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise
print(np.hstack((a,b))) # horizontal stacking - column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [1]:
import numpy as np

In [2]:
# splittinng

c = np.array ([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [3]:
split = np.hsplit(c,3) # Horizontal split

for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [4]:
 # 7 Mathematical Operatiion on Array

In [5]:
a = np.array([10,20,40, -30])
print(a)

[ 10  20  40 -30]


In [6]:
print(a+10) # add
print(a-30) # subs
print(a*2) # multiply
print(a/10) # divide

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [7]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [8]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [9]:
print(np.sin(b))

[ 0.84147098 -0.7568025   0.41211849]


In [11]:
print(np.cos(b))
print(np.tan(b))
#print(np.sec(b))

[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


In [12]:
 # 8 Mathematical Operatiion on Multiple Array

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [16]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
print(np.dot(a,b)) # dot product

32


In [18]:
print(a.T) # Transpose

[1 2 3]


In [19]:
t = np.array([[1,2,3],
             [4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [1]:
 import numpy as np

In [2]:
# 9 Statistical Functions

In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
print(np.sum(a))

21


In [7]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [8]:
# 10 Array Comparison

In [9]:
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [10]:
print(a == b) # comparing each elements
print(np.array_equal(a,b)) # comparing complete array

[False  True False]
False


In [14]:
# 11 Broadcasting

In [12]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)

[6 7 8 9]


In [13]:
c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [15]:
# 12 Handling with nan & inf

In [18]:
data1 = np.array([1,2, np.nan, 4, np.inf])  # inf= infinite value
print(data1)

[ 1.  2. nan  4. inf]


In [17]:
 print(np.isnan(data1))

[False False  True False False]


In [19]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [20]:
# save and load arrays

In [23]:
arr = np.array([2,5,0,0])
print(arr)
np.save('my_array.npy', arr)

[2 5 0 0]


In [25]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[2 5 0 0]
