In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.4 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.4 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.4 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.4 MB 3.6 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.4 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.4 MB 3.4 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.4 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.4 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.4 MB 3.4 MB/s eta 0:00:02
   ----------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [4]:
## 1. creating arrays

In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [14]:
print(arr_list1.ndim)

1


In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr_list1_2.ndim)

2


In [11]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_25 = np.array([[list1, list2, list3]])
print(arr_list1_25)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(arr_list1_25.ndim)

3


In [17]:
# 2 . numpy array attributes

In [20]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [21]:
print("Shape", arr1.shape)
print("Size", arr1.size)
print("dType", arr1.dtype)
print("n_dim", arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [27]:
 # create 1D array and find its attribute

In [25]:
arr4 = np.array([1,2.0,3.5])
print(arr4)

[1.  2.  3.5]


In [26]:
print("Shape", arr4.shape)
print("Size", arr4.size)
print("dType", arr4.dtype)
print("n_dim", arr4.ndim)

Shape (3,)
Size 3
dType float64
n_dim 1


In [29]:
# create 3D array and  find it's attribute

In [30]:
arr5 = np.array([[[1,20.5, 30.6], [2, 25.3, 28.4], [3, 35.3, 40.9]]])
print(arr5)

[[[ 1.  20.5 30.6]
  [ 2.  25.3 28.4]
  [ 3.  35.3 40.9]]]


In [31]:
print("Shape", arr5.shape)
print("Size", arr5.size)
print("dType", arr5.dtype)
print("n_dim", arr5.ndim)

Shape (1, 3, 3)
Size 9
dType float64
n_dim 3


In [32]:
  # Array initialization method

In [34]:
# zeros array

zero_arry = np.zeros((2,3))
print(zero_arry)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# one array

In [36]:
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [37]:
# full array

In [38]:
full_arr = np.full((3,2), 9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]
